on:
  push:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List changed files
        run: |
          git --no-pager diff --name-only $GITHUB_SHA..$GITHUB_BASE_REF
